name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the contianer instead the VM.
    container: golangci/golangci-lint:v1.27.0-alpine
    steps:
      - uses: actions/checkout@v1
      - run: golangci-lint run -E goimports

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: make test
